// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: microservice.proto
// Original file comments:
// XXXXXXX1XXXXXXXXX2XXXXXXXXX3XXXXXXXXX4XXXXXXXXX5XXXXXXXXX6XXXXXXXXX7XXXXXXXXX8XXXXXXXXX9XXXXXXXXXCXXXX5
// Microservice schema ("contract") between EA (client) and Experior (server) read by "protoc" executable
#ifndef GRPC_microservice_2eproto__INCLUDED
#define GRPC_microservice_2eproto__INCLUDED

#include "microservice.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace microservice {

// Define each constituent "service" available to the "microservice" package
//
class MakeComparisons final {
 public:
  static constexpr char const* service_full_name() {
    return "microservice.MakeComparisons";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Define the methods available to each service by using this syntax (keyword in "[]" is optional):
    // rpc <method_name>( [stream] <request_message_type> ) returns ( [stream] <response_message_type> ) {}
    // "{}" typically empty, else to bind method to an HTTP prompt so web browsers can run it as client
    //
    virtual ::grpc::Status Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::microservice::MessageTypeB* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>> AsyncIs_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>>(AsyncIs_x_GT_yRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>> PrepareAsyncIs_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>>(PrepareAsyncIs_x_GT_yRaw(context, request, cq));
    }
    virtual ::grpc::Status Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::microservice::MessageTypeB* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>> AsyncIs_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>>(AsyncIs_y_LT_zRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>> PrepareAsyncIs_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>>(PrepareAsyncIs_y_LT_zRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Define the methods available to each service by using this syntax (keyword in "[]" is optional):
      // rpc <method_name>( [stream] <request_message_type> ) returns ( [stream] <response_message_type> ) {}
      // "{}" typically empty, else to bind method to an HTTP prompt so web browsers can run it as client
      //
      virtual void Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>* AsyncIs_x_GT_yRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>* PrepareAsyncIs_x_GT_yRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>* AsyncIs_y_LT_zRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::microservice::MessageTypeB>* PrepareAsyncIs_y_LT_zRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::microservice::MessageTypeB* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>> AsyncIs_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>>(AsyncIs_x_GT_yRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>> PrepareAsyncIs_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>>(PrepareAsyncIs_x_GT_yRaw(context, request, cq));
    }
    ::grpc::Status Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::microservice::MessageTypeB* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>> AsyncIs_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>>(AsyncIs_y_LT_zRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>> PrepareAsyncIs_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>>(PrepareAsyncIs_y_LT_zRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, std::function<void(::grpc::Status)>) override;
      void Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, std::function<void(::grpc::Status)>) override;
      void Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* AsyncIs_x_GT_yRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* PrepareAsyncIs_x_GT_yRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* AsyncIs_y_LT_zRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* PrepareAsyncIs_y_LT_zRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Is_x_GT_y_;
    const ::grpc::internal::RpcMethod rpcmethod_Is_y_LT_z_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Define the methods available to each service by using this syntax (keyword in "[]" is optional):
    // rpc <method_name>( [stream] <request_message_type> ) returns ( [stream] <response_message_type> ) {}
    // "{}" typically empty, else to bind method to an HTTP prompt so web browsers can run it as client
    //
    virtual ::grpc::Status Is_x_GT_y(::grpc::ServerContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response);
    virtual ::grpc::Status Is_y_LT_z(::grpc::ServerContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Is_x_GT_y : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Is_x_GT_y() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Is_x_GT_y() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_x_GT_y(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIs_x_GT_y(::grpc::ServerContext* context, ::microservice::MessageTypeA* request, ::grpc::ServerAsyncResponseWriter< ::microservice::MessageTypeB>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Is_y_LT_z : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Is_y_LT_z() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Is_y_LT_z() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_y_LT_z(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIs_y_LT_z(::grpc::ServerContext* context, ::microservice::MessageTypeA* request, ::grpc::ServerAsyncResponseWriter< ::microservice::MessageTypeB>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Is_x_GT_y<WithAsyncMethod_Is_y_LT_z<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Is_x_GT_y : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Is_x_GT_y() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::microservice::MessageTypeA, ::microservice::MessageTypeB>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response) { return this->Is_x_GT_y(context, request, response); }));}
    void SetMessageAllocatorFor_Is_x_GT_y(
        ::grpc::MessageAllocator< ::microservice::MessageTypeA, ::microservice::MessageTypeB>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::microservice::MessageTypeA, ::microservice::MessageTypeB>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Is_x_GT_y() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_x_GT_y(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Is_x_GT_y(
      ::grpc::CallbackServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Is_y_LT_z : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Is_y_LT_z() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::microservice::MessageTypeA, ::microservice::MessageTypeB>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response) { return this->Is_y_LT_z(context, request, response); }));}
    void SetMessageAllocatorFor_Is_y_LT_z(
        ::grpc::MessageAllocator< ::microservice::MessageTypeA, ::microservice::MessageTypeB>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::microservice::MessageTypeA, ::microservice::MessageTypeB>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Is_y_LT_z() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_y_LT_z(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Is_y_LT_z(
      ::grpc::CallbackServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Is_x_GT_y<WithCallbackMethod_Is_y_LT_z<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Is_x_GT_y : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Is_x_GT_y() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Is_x_GT_y() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_x_GT_y(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Is_y_LT_z : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Is_y_LT_z() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Is_y_LT_z() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_y_LT_z(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Is_x_GT_y : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Is_x_GT_y() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Is_x_GT_y() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_x_GT_y(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIs_x_GT_y(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Is_y_LT_z : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Is_y_LT_z() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Is_y_LT_z() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_y_LT_z(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIs_y_LT_z(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Is_x_GT_y : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Is_x_GT_y() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Is_x_GT_y(context, request, response); }));
    }
    ~WithRawCallbackMethod_Is_x_GT_y() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_x_GT_y(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Is_x_GT_y(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Is_y_LT_z : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Is_y_LT_z() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Is_y_LT_z(context, request, response); }));
    }
    ~WithRawCallbackMethod_Is_y_LT_z() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Is_y_LT_z(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Is_y_LT_z(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Is_x_GT_y : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Is_x_GT_y() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::microservice::MessageTypeA, ::microservice::MessageTypeB>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::microservice::MessageTypeA, ::microservice::MessageTypeB>* streamer) {
                       return this->StreamedIs_x_GT_y(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Is_x_GT_y() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Is_x_GT_y(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIs_x_GT_y(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::microservice::MessageTypeA,::microservice::MessageTypeB>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Is_y_LT_z : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Is_y_LT_z() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::microservice::MessageTypeA, ::microservice::MessageTypeB>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::microservice::MessageTypeA, ::microservice::MessageTypeB>* streamer) {
                       return this->StreamedIs_y_LT_z(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Is_y_LT_z() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Is_y_LT_z(::grpc::ServerContext* /*context*/, const ::microservice::MessageTypeA* /*request*/, ::microservice::MessageTypeB* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIs_y_LT_z(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::microservice::MessageTypeA,::microservice::MessageTypeB>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Is_x_GT_y<WithStreamedUnaryMethod_Is_y_LT_z<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Is_x_GT_y<WithStreamedUnaryMethod_Is_y_LT_z<Service > > StreamedService;
};

}  // namespace microservice


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_microservice_2eproto__INCLUDED
