// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: microservice.proto

#include "microservice.pb.h"
#include "microservice.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace microservice {

static const char* MakeComparisons_method_names[] = {
  "/microservice.MakeComparisons/Is_x_GT_y",
  "/microservice.MakeComparisons/Is_y_LT_z",
};

std::unique_ptr< MakeComparisons::Stub> MakeComparisons::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MakeComparisons::Stub> stub(new MakeComparisons::Stub(channel, options));
  return stub;
}

MakeComparisons::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Is_x_GT_y_(MakeComparisons_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Is_y_LT_z_(MakeComparisons_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MakeComparisons::Stub::Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::microservice::MessageTypeB* response) {
  return ::grpc::internal::BlockingUnaryCall< ::microservice::MessageTypeA, ::microservice::MessageTypeB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Is_x_GT_y_, context, request, response);
}

void MakeComparisons::Stub::async::Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::microservice::MessageTypeA, ::microservice::MessageTypeB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Is_x_GT_y_, context, request, response, std::move(f));
}

void MakeComparisons::Stub::async::Is_x_GT_y(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Is_x_GT_y_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* MakeComparisons::Stub::PrepareAsyncIs_x_GT_yRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::microservice::MessageTypeB, ::microservice::MessageTypeA, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Is_x_GT_y_, context, request);
}

::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* MakeComparisons::Stub::AsyncIs_x_GT_yRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIs_x_GT_yRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MakeComparisons::Stub::Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::microservice::MessageTypeB* response) {
  return ::grpc::internal::BlockingUnaryCall< ::microservice::MessageTypeA, ::microservice::MessageTypeB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Is_y_LT_z_, context, request, response);
}

void MakeComparisons::Stub::async::Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::microservice::MessageTypeA, ::microservice::MessageTypeB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Is_y_LT_z_, context, request, response, std::move(f));
}

void MakeComparisons::Stub::async::Is_y_LT_z(::grpc::ClientContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Is_y_LT_z_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* MakeComparisons::Stub::PrepareAsyncIs_y_LT_zRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::microservice::MessageTypeB, ::microservice::MessageTypeA, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Is_y_LT_z_, context, request);
}

::grpc::ClientAsyncResponseReader< ::microservice::MessageTypeB>* MakeComparisons::Stub::AsyncIs_y_LT_zRaw(::grpc::ClientContext* context, const ::microservice::MessageTypeA& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIs_y_LT_zRaw(context, request, cq);
  result->StartCall();
  return result;
}

MakeComparisons::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MakeComparisons_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MakeComparisons::Service, ::microservice::MessageTypeA, ::microservice::MessageTypeB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MakeComparisons::Service* service,
             ::grpc::ServerContext* ctx,
             const ::microservice::MessageTypeA* req,
             ::microservice::MessageTypeB* resp) {
               return service->Is_x_GT_y(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MakeComparisons_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MakeComparisons::Service, ::microservice::MessageTypeA, ::microservice::MessageTypeB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MakeComparisons::Service* service,
             ::grpc::ServerContext* ctx,
             const ::microservice::MessageTypeA* req,
             ::microservice::MessageTypeB* resp) {
               return service->Is_y_LT_z(ctx, req, resp);
             }, this)));
}

MakeComparisons::Service::~Service() {
}

::grpc::Status MakeComparisons::Service::Is_x_GT_y(::grpc::ServerContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MakeComparisons::Service::Is_y_LT_z(::grpc::ServerContext* context, const ::microservice::MessageTypeA* request, ::microservice::MessageTypeB* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace microservice
#include <grpcpp/ports_undef.inc>

