# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import microservice_pb2 as microservice__pb2


class MakeComparisonsStub(object):
    """Define each constituent "service" available to the "microservice" package

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Is_x_GT_y = channel.unary_unary(
                '/microservice.MakeComparisons/Is_x_GT_y',
                request_serializer=microservice__pb2.MessageTypeA.SerializeToString,
                response_deserializer=microservice__pb2.MessageTypeB.FromString,
                _registered_method=True)
        self.Is_y_LT_z = channel.unary_unary(
                '/microservice.MakeComparisons/Is_y_LT_z',
                request_serializer=microservice__pb2.MessageTypeA.SerializeToString,
                response_deserializer=microservice__pb2.MessageTypeB.FromString,
                _registered_method=True)


class MakeComparisonsServicer(object):
    """Define each constituent "service" available to the "microservice" package

    """

    def Is_x_GT_y(self, request, context):
        """Define the methods available to each service by using this syntax (keyword in "[]" is optional):
        rpc <method_name>( [stream] <request_message_type> ) returns ( [stream] <response_message_type> ) {}
        "{}" typically empty, else to bind method to an HTTP prompt so web browsers can run it as client

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Is_y_LT_z(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MakeComparisonsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Is_x_GT_y': grpc.unary_unary_rpc_method_handler(
                    servicer.Is_x_GT_y,
                    request_deserializer=microservice__pb2.MessageTypeA.FromString,
                    response_serializer=microservice__pb2.MessageTypeB.SerializeToString,
            ),
            'Is_y_LT_z': grpc.unary_unary_rpc_method_handler(
                    servicer.Is_y_LT_z,
                    request_deserializer=microservice__pb2.MessageTypeA.FromString,
                    response_serializer=microservice__pb2.MessageTypeB.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microservice.MakeComparisons', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('microservice.MakeComparisons', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MakeComparisons(object):
    """Define each constituent "service" available to the "microservice" package

    """

    @staticmethod
    def Is_x_GT_y(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservice.MakeComparisons/Is_x_GT_y',
            microservice__pb2.MessageTypeA.SerializeToString,
            microservice__pb2.MessageTypeB.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Is_y_LT_z(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservice.MakeComparisons/Is_y_LT_z',
            microservice__pb2.MessageTypeA.SerializeToString,
            microservice__pb2.MessageTypeB.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
