# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: microservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'microservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12microservice.proto\x12\x0cmicroservice\"/\n\x0cMessageTypeA\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x1d\n\x0cMessageTypeB\x12\r\n\x05reply\x18\x01 \x01(\x08\x32\x9f\x01\n\x0fMakeComparisons\x12\x45\n\tIs_x_GT_y\x12\x1a.microservice.MessageTypeA\x1a\x1a.microservice.MessageTypeB\"\x00\x12\x45\n\tIs_y_LT_z\x12\x1a.microservice.MessageTypeA\x1a\x1a.microservice.MessageTypeB\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPEA']._serialized_start=36
  _globals['_MESSAGETYPEA']._serialized_end=83
  _globals['_MESSAGETYPEB']._serialized_start=85
  _globals['_MESSAGETYPEB']._serialized_end=114
  _globals['_MAKECOMPARISONS']._serialized_start=117
  _globals['_MAKECOMPARISONS']._serialized_end=276
# @@protoc_insertion_point(module_scope)
